POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjQ1YmRiNjExN2ZjNDlhZTQzN2U5NDM2IiwiaWF0IjoxNjkwMzgzODkyfQ.tZ_5i9iwAhV60IiLPiZwVdSpg8-Ou3rnNdBTfP9i9lE

{
  "title": "COMMENT TESTING",
  "author": "McComment",
  "url": "www.test.com",
  "likes": 1,
  "userId": "645bdb6117fc49ae437e9436"
}
###
POST http://localhost:3003/api/blogs/64c138054f0653b27ec50fcc/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjQ1YmRiNjExN2ZjNDlhZTQzN2U5NDM2IiwiaWF0IjoxNjkwMzgzODkyfQ.tZ_5i9iwAhV60IiLPiZwVdSpg8-Ou3rnNdBTfP9i9lE

{
  "comment": "2ND TEST"
}

###
GET http://localhost:3003/api/blogs