# fly.toml file generated for blue-cloud-9892 on 2023-03-31T22:02:29-04:00

app = "blue-cloud-9892"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
