POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjQ1NjY2N2UyMmIwM2Y3YmY5NTczZGM1IiwiaWF0IjoxNjgzNTAwNzAwfQ.sbzJxLp11txw8ocZKV7BwjZh4Peut0ipeAksuGgVXOg

{
  "title": "DELETE TEST",
  "author": "DEAD",
  "url": "www.rip.com",
  "likes": 900,
  "userId": "6456667e22b03f7bf9573dc5"
}

###
GET http://localhost:3003/api/blogs