POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjQ1NjY2N2UyMmIwM2Y3YmY5NTczZGM1IiwiaWF0IjoxNjgzMzkxMTk5fQ.oM9CKImsN1dPSoLHtLIm26RcvQfm1rq0kOq-uqqp6UU

{
  "title": "token auth test 3",
  "author": "JRR Token III",
  "url": "www.jrr3.com",
  "likes": 333,
  "userId": "6456669b22b03f7bf9573dc9"
}

###
GET http://localhost:3003/api/blogs